jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "11"
      script: 
        - npm install
        - npm run build
      deploy:
        provider: npm
        email: "$USER_EMAIL"
        api_key: "$USER_TOKEN"
        skip_cleanup: true
        on:
          tags: true